/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "lib_crypto.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// [변경] 파이썬에서 시스템 차원과 파라미터를 받아옴
//
extern __declspec(dllexport) void InitCrypto(int in_n, int in_m, int in_p, double in_s, double in_L, double in_r);

// [변경] 실수 배열 포인터와 길이를 받음 (Generic Encrypt)
//
extern __declspec(dllexport) char* EncryptVector(double* valuesPtr, int length, int* sizePtr);

// [변경] 복호화 후 배열 반환 (길이는 전역변수 m 사용 가능하지만, 인자로 받아도 됨)
// 여기서는 편의상 m(입력차원) 만큼 복호화한다고 가정하거나,
// DecryptU 처럼 특정 용도라면 m을 사용. 범용성을 위해 요청한 크기(outLen)만큼 반환.
//
extern __declspec(dllexport) double* DecryptVector(void* dataPtr, int dataLen, int outLen);
extern __declspec(dllexport) void FreePtr(void* ptr);

#ifdef __cplusplus
}
#endif
